class PipTools < Formula
  include Language::Python::Virtualenv

  desc "Locking and sync for Pip requirements files"
  homepage "https://pip-tools.readthedocs.io"
  url "https://files.pythonhosted.org/packages/fd/01/f0055058a86a888f32ac794fa68d5a25c2d2f7a3e8181474b711faaa2145/pip-tools-7.3.0.tar.gz"
  sha256 "8e9c99127fe024c025b46a0b2d15c7bd47f18f33226cf7330d35493663fc1d1d"
  license "BSD-3-Clause"

  bottle do
    rebuild 1
    sha256 cellar: :any_skip_relocation, arm64_sonoma:   "51d348029b31f2a4d9bedb4440279041c692fabf1b028391f182fa57d3c93f90"
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "e7d42fcc1d9cf18973401be08a7bdb4c5fec00c34640c2b3a93ef085c27310cb"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "5b91f9a23407da6137e482c615f3a446f3752db42f85622788d262f3204bda8f"
    sha256 cellar: :any_skip_relocation, sonoma:         "a178cc9d0c1152401b7c83fd4e5c075fce1004086055266006a414f24d0e6214"
    sha256 cellar: :any_skip_relocation, ventura:        "853386f9765cbe1cc8a1431512995145dfcb9457c3bd6df9652c8d941422e943"
    sha256 cellar: :any_skip_relocation, monterey:       "05441fcb88918ab4608ca4e3b894c7f46e629e83f4d13aab1b2bbb2aabb68a2c"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "ec734235c6bdc7fc1913f9a71bc2f2afce0b290fdc5cf7b878a8e3fdbf2b59aa"
  end

  depends_on "python-build"
  depends_on "python-packaging"
  depends_on "python@3.11"

  resource "click" do
    url "https://files.pythonhosted.org/packages/72/bd/fedc277e7351917b6c4e0ac751853a97af261278a4c7808babafa8ef2120/click-8.1.6.tar.gz"
    sha256 "48ee849951919527a045bfe3bf7baa8a959c423134e1a5b98c05c20ba75a1cbd"
  end

  resource "pyproject-hooks" do
    url "https://files.pythonhosted.org/packages/25/c1/374304b8407d3818f7025457b7366c8e07768377ce12edfe2aa58aa0f64c/pyproject_hooks-1.0.0.tar.gz"
    sha256 "f271b298b97f5955d53fb12b72c1fb1948c22c1a6b70b315c54cedaca0264ef5"
  end

  resource "wheel" do
    url "https://files.pythonhosted.org/packages/c9/3d/02a14af2b413d7abf856083f327744d286f4468365cddace393a43d9d540/wheel-0.41.1.tar.gz"
    sha256 "12b911f083e876e10c595779709f8a88a59f45aacc646492a67fe9ef796c1b47"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    (testpath/"requirements.in").write <<~EOS
      pip-tools
      typing-extensions
    EOS

    compiled = shell_output("#{bin}/pip-compile requirements.in -q -o -")
    assert_match "This file is autogenerated by pip-compile", compiled
    assert_match "# via pip-tools", compiled
  end
end
