class Mockolo < Formula
  desc "Efficient Mock Generator for Swift"
  homepage "https://github.com/uber/mockolo"
  url "https://github.com/uber/mockolo/archive/refs/tags/2.0.0.tar.gz"
  sha256 "ec5a4852012f511d430e9207f141a548374b36c39ee46c9878360d2fa400246b"
  license "Apache-2.0"

  bottle do
    sha256 cellar: :any,                 arm64_monterey: "ec9107e0879903c87c985b28d2fe74bd9b31774afd91a146e3c754eb9eb811f7"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "0b606ab655409f007af9cad55687192f91e1c627339a654ca5e272eb0309a5f2"
    sha256 cellar: :any,                 monterey:       "440d4ed1a80e999b72532e9f8b4421adb41715982115d99655c19d85721a467c"
    sha256 cellar: :any_skip_relocation, big_sur:        "bbc38d67aac3b847b771e0bc63d5ae9f7dbca74c053b912592510da09486dc6a"
  end

  depends_on xcode: ["14.0", :build]

  uses_from_macos "swift"

  def install
    system "swift", "build", "-c", "release", "--disable-sandbox", "--product", "mockolo"
    bin.install ".build/release/mockolo"
  end

  test do
    (testpath/"testfile.swift").write <<~EOS
      /// @mockable
      public protocol Foo {
          var num: Int { get set }
          func bar(arg: Float) -> String
      }
    EOS
    system "#{bin}/mockolo", "-srcs", testpath/"testfile.swift", "-d", testpath/"GeneratedMocks.swift"
    assert_predicate testpath/"GeneratedMocks.swift", :exist?
    output = <<~EOS.gsub(/\s+/, "").strip
      ///
      /// @Generated by Mockolo
      ///
      public class FooMock: Foo {
        public init() { }
        public init(num: Int = 0) {
            self.num = num
        }

        public private(set) var numSetCallCount = 0
        public var num: Int = 0 { didSet { numSetCallCount += 1 } }

        public private(set) var barCallCount = 0
        public var barHandler: ((Float) -> (String))?
        public func bar(arg: Float) -> String {
            barCallCount += 1
            if let barHandler = barHandler {
                return barHandler(arg)
            }
            return ""
        }
      }
    EOS
    assert_equal output, shell_output("cat #{testpath/"GeneratedMocks.swift"}").gsub(/\s+/, "").strip
  end
end
