class PipTools < Formula
  include Language::Python::Virtualenv

  desc "Locking and sync for Pip requirements files"
  homepage "https://pip-tools.readthedocs.io"
  url "https://files.pythonhosted.org/packages/b1/5a/29da7316a6b36a5045454ced356849fd17538a3d53adc9af1c2474de1032/pip-tools-6.12.2.tar.gz"
  sha256 "8b903696df4598b10d469026ef9995c5f9a874b416e88e7a214884ebe4a70245"
  license "BSD-3-Clause"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "977e756eb5fd745220792b73f8dc7fe456ba2ec682aca1a08a1d05b1d3ba1ca8"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "28604d7abc103246a89030f92edc97788d3397ad691aa97b7c0d7a7a9b130b4e"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "0c7dcbe50f489be7b2d08bb60f9d3887e31d5b7797bd82cac2b568faf0675e99"
    sha256 cellar: :any_skip_relocation, ventura:        "647db1edae30e803ee704c7313c050639118328f915048e528656be262cb183a"
    sha256 cellar: :any_skip_relocation, monterey:       "9d737c8e5f849cecedeb20306dffb46345d123d1d35ae64acd4c3923ae6b6936"
    sha256 cellar: :any_skip_relocation, big_sur:        "04730153a8be86c5cad8394dc6405ee2c1a176be1d622eb2d45e2a504c91c590"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "5a7970b84dfe1929a1cd377659f24561c4170e606582395d89239c201b529ca1"
  end

  depends_on "python@3.11"

  resource "build" do
    url "https://files.pythonhosted.org/packages/de/1c/fb62f81952f0e74c3fbf411261d1adbdd2d615c89a24b42d0fe44eb4bcf3/build-0.10.0.tar.gz"
    sha256 "d5b71264afdb5951d6704482aac78de887c80691c52b88a9ad195983ca2c9269"
  end

  resource "click" do
    url "https://files.pythonhosted.org/packages/59/87/84326af34517fca8c58418d148f2403df25303e02736832403587318e9e8/click-8.1.3.tar.gz"
    sha256 "7682dc8afb30297001674575ea00d1814d808d6a36af415a82bd481d37ba7b8e"
  end

  resource "packaging" do
    url "https://files.pythonhosted.org/packages/47/d5/aca8ff6f49aa5565df1c826e7bf5e85a6df852ee063600c1efa5b932968c/packaging-23.0.tar.gz"
    sha256 "b6ad297f8907de0fa2fe1ccbd26fdaf387f5f47c7275fedf8cce89f99446cf97"
  end

  resource "pyproject_hooks" do
    url "https://files.pythonhosted.org/packages/25/c1/374304b8407d3818f7025457b7366c8e07768377ce12edfe2aa58aa0f64c/pyproject_hooks-1.0.0.tar.gz"
    sha256 "f271b298b97f5955d53fb12b72c1fb1948c22c1a6b70b315c54cedaca0264ef5"
  end

  resource "wheel" do
    url "https://files.pythonhosted.org/packages/a2/b8/6a06ff0f13a00fc3c3e7d222a995526cbca26c1ad107691b6b1badbbabf1/wheel-0.38.4.tar.gz"
    sha256 "965f5259b566725405b05e7cf774052044b1ed30119b5d586b2703aafe8719ac"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    (testpath/"requirements.in").write <<~EOS
      pip-tools
      typing-extensions
    EOS

    compiled = shell_output("#{bin}/pip-compile requirements.in -q -o -")
    assert_match "This file is autogenerated by pip-compile", compiled
    assert_match "# via pip-tools", compiled
  end
end
