class Sqlc < Formula
  desc "Generate type safe Go from SQL"
  homepage "https://sqlc.dev/"
  url "https://github.com/kyleconroy/sqlc/archive/v1.17.2.tar.gz"
  sha256 "6c8e1b66d11c4aacffad8c5e9e7586df12e5b1c24f957d4c5d78c3789da5de56"
  license "MIT"
  head "https://github.com/kyleconroy/sqlc.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_ventura:  "4d68c12c07963bcfbc2b633464e7fa77a36bc73a2bb3063a5b5b6f6c44b599d0"
    sha256 cellar: :any_skip_relocation, arm64_monterey: "45b3931a59c064db42a1365fe51b32e816585ba9b56eec3865f42553b404e6f6"
    sha256 cellar: :any_skip_relocation, arm64_big_sur:  "2cdfe83d3ed6b8b629c8eb8bbee56f83500ce7a1028ba838c27d7e15f8368e84"
    sha256 cellar: :any_skip_relocation, ventura:        "b7e8cbb869b60c4c6d6db89c78a140dfcfa9af0e78ba76fdcfaca4ebdc4b5cb2"
    sha256 cellar: :any_skip_relocation, monterey:       "f51736c9c1ab490b47097eb02218dd096c82f5156e6154930416d80b2b59011b"
    sha256 cellar: :any_skip_relocation, big_sur:        "7c00f7c1f7ee2a3749d88ba13d698c9d61d99e9dd140bf782fe3bf0aeb1679cf"
    sha256 cellar: :any_skip_relocation, x86_64_linux:   "342a37d7534e75859571bf5dcecb847d6643d6c831dc6a8057c14f02480e14ab"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args, "-ldflags", "-s -w", "./cmd/sqlc"

    generate_completions_from_executable(bin/"sqlc", "completion")
  end

  test do
    (testpath/"sqlc.json").write <<~SQLC
      {
        "version": "1",
        "packages": [
          {
            "name": "db",
            "path": ".",
            "queries": "query.sql",
            "schema": "query.sql",
            "engine": "postgresql"
          }
        ]
      }
    SQLC

    (testpath/"query.sql").write <<~EOS
      CREATE TABLE foo (bar text);

      -- name: SelectFoo :many
      SELECT * FROM foo;
    EOS

    system bin/"sqlc", "generate"
    assert_predicate testpath/"db.go", :exist?
    assert_predicate testpath/"models.go", :exist?
    assert_match "// Code generated by sqlc. DO NOT EDIT.", File.read(testpath/"query.sql.go")
  end
end
